# Generated by Django 2.0 on 2018-12-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ski', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mountain',
            name='users_who_like',
            field=models.ManyToManyField(related_name='liked_mountain', to='ski.User'),
        ),
    ]
